<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLeoxcka\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLeoxcka/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLeoxcka.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLeoxcka\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLeoxcka\appProdProjectContainer(array(
    'container.build_hash' => 'Leoxcka',
    'container.build_id' => 'da66a2ea',
    'container.build_time' => 1576497404,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLeoxcka');
