<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1apc5iz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1apc5iz/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1apc5iz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1apc5iz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1apc5iz\appProdProjectContainer(array(
    'container.build_hash' => '1apc5iz',
    'container.build_id' => '35b7c082',
    'container.build_time' => 1560921020,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1apc5iz');
