<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBt7xr65\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBt7xr65/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBt7xr65.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBt7xr65\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBt7xr65\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bt7xr65',
    'container.build_id' => 'ba69903f',
    'container.build_time' => 1574746073,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBt7xr65');
